basic_settings:
  site_title: WeiZhuDesign
  favicon_image: /images/favicon.png

header_settings:
  logo_image:
  logo_width: 

menu_settings:
  menu_items:
    - title: Work
      url: /
    - title: Resume
      url: /resume
    - title: Contact
      url: /contact
    - title: Blog
      url: /blog/

footer_settings:
  logo_image: images/logo.png
  logo_width: 60
  footer_tagline:

social_settings:
  github_url: 'https://github.com/weizhudesign'

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
  recommendation_js: ""
